version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        
      - name: product
        identifier: raw_gz_product

      - name: ship
        identifier: raw_gz_ship
      
      - name: adwords
        identifier: raw_gz_adwords
      
      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo
      
      - name: facebook
        identifier: raw_gz_facebook

models:
  - name: finance_campaigns_day
    description: global kpi
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
      - name: average_basket
        description: average basket cost for each day 
    tests:
      - not_null:
          column_name:
            - ads_margin
            - average_basket

  - name: int_campaigns
    description: data from all campaigns
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
      - not_null:
          column_name:
            - paid_source
            - campaign_name
